
#服务端口号
server:
  port: 8001
#服务名称
spring:
  application:
    name: cloud-paymet-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                   #当前数据源类型
    driver-class-name: org.gjt.mm.mysql.Driver                      #驱动包
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml                       #mapper路径
  type-aliases-package: com.njhr.entity

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
