server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
#          从服务注册中心动态拿到地址，避免端口写死
#          此lb为loadbalance的缩写，表示负载均衡，如果写成http则报错
          uri: lb://CLOUD-PAYMET-SERVICE
          filters:
            - AddRequestHeader=X-Request-Id,1024   # 过滤器工厂，会在匹配的求请求头上加上一对请求头，名称为X-request-id 值为1024
#            先执行断言匹配，然后再过滤，所有即使此时加入请求头，使用curl测试地址不加请求头是不正确的，需要加上请求头之后，然后过滤器会再给加一个请求头，放行
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
##            从该时间之后生效
#            - After=2020-11-08T10:59:34.102+08:00[Asia/Shanghai]

#            - Before=2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
#            - Between=2020-03-08T10:59:34.102+08:00[Asia/Shanghai] ,  2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
#            - Cookie=username,atguigu    #并且Cookie是username=zhangshuai才能访问   curl localhost:9527/payment/get/1 --cookie username=atguigu
#            - Header=X-Request-Id, \d+   #请求头中要有X-Request-Id属性并且值为整数的正则表达式  curl localhost:9527/payment/get/1 -H "X-Request-id:23"
#            - Host=**.atguigu.com       #请求host中必须携带此地址   curl localhost:9527/payment/get/1 -H "Host:wwww.atguigu.com"
#            - Method=GET                #请求方法为get
#            - Query=username, \d+ #要有参数名称并且是正整数才能路由  就是查询语句，例如 localhost:8080/GGShip/payment?username=30

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMET-SERVICE
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka