
#服务端口号
server:
  port: 8001
#服务名称
spring:
  application:
    name: cloud-paymet-service
#    服务链路监控
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                   #当前数据源类型
    driver-class-name: org.gjt.mm.mysql.Driver                      #驱动包
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath*:mapper/*.xml                       #mapper路径
  type-aliases-package: com.njhr.entity

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      单机配置
#      defaultZone: http://localhost:7001/eureka
#      注册中心集群配置
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#      主机名称修改
  instance:
    instance-id: payment8001
#    鼠标放在服务主机上有ip地址显示
    prefer-ip-address: true
