


  eureka:
    client:
      register-with-eureka: true    #表识不向注册中心注册自己
      fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka/

  spring:
    application:
      name: cloud-provider-hystrix-order
  server:
    port: 80

#  处理自身容错开启
  feign:
    hystrix:
      enabled: true
    client:
      config:
        default:  # 服务名，default表示所有服务
          connectTimeout: 10000
          readTimeout: 60000
          loggerLevel: full  # full | basic | none | headers
          #requestInterceptors: 拦截器





