


  eureka:
    client:
      register-with-eureka: true    #表识不向注册中心注册自己
      fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka/

  spring:
    application:
      name: cloud-provider-hystrix-order
  server:
    port: 80

#  处理自身容错开启
  feign:
    hystrix:
      enabled: true
#注意
#openfeign开启自身容错后，需要同时开启ribbon的超时控制以及hystrix的超时设置，否则将会一直超时，不会接受服务提供者返回的数据，直接调用服务降级的方法

  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 15000


  ribbon:
    ReadTimeout:  5000
    ConnectTimeout: 500






